version: '3.8'
services:
  demo_runner:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf